[TP2-6] - create edit for user in userServices
StayTeeVone/pepper-team-front pull request #2
Opened 2023-02-18 20:11 UTC by Shapovall

A function was added to edit the user in the user service.

2023-02-18 20:14 UTC, StayTeeVone approved these changes
Good.

2023-02-18 20:23 UTC, GOSTT22 approved these changes

2023-02-18 20:31 UTC, OleynikBogdan approved these changes

2023-02-18 21:01 UTC, buba3230 commented on src/app/custom-components/users.service.ts
> +        return this.http.put<any>(this.url + '/' + updatedUser.id_user, updatedUser).pipe(
Not any! You should pass an object with some type. Your interface type

2023-02-18 21:02 UTC, buba3230 requested changes

2023-02-18 21:02 UTC, buba3230 commented on src/app/custom-components/users.service.ts
> +            tap(() => console.log('updated user')),
Remove redundant tap from here

2023-02-19 10:08 UTC, GOSTT22 approved these changes

2023-02-19 10:15 UTC, StayTeeVone requested changes
you know

2023-02-23 14:23 UTC, StayTeeVone approved these changes

2023-02-23 14:39 UTC, OleynikBogdan approved these changes

2023-02-23 23:27 UTC, closed without merging